service: auth-name
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:eu-central-1:590183937995:table/Users"
# plugins:
#   - serverless-offline

functions:
  auth:
    handler: ./dist/index.auth
    events:
      - http:
          path: auth/{action}
          method: "any"
          cors: true
          # authorizer: aws_iam
    environment:
      DYNAMODB_TABLE: Users
    # iamRoleStatements:
    #   - Effect: Allow
    #     Action:
    #       - dynamodb:GetItem
    #     Resource: "arn:aws:dynamodb:eu-central-1:590183937995:table/Users"

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
