service: auth-name
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

# plugins:
#   - serverless-offline

functions:
  auth:
    handler: ./dist/index.auth
    events:
      - http:
          path: auth/{action}
          method: "any"
          cors: true
          authorizer: aws_iam
    environment:
      DYNAMODB_TABLE: Users

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
